# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - os: linux
      dist: trusty
      r: devel

    - os: linux
      dist: focal
      r: release

  allow_failures:
    - os: linux
      dist: focal
      r: devel


language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: never
    on_failure: never