# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r



matrix:
  include:
    - os: linux
      dist: bionic
      r: devel

    - os: linux
      dist: bionic
      r: release

  allow_failures:
    - os: linux
      dist: bionic
      r: devel


language: R
sudo: false
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

notifications:
  email:
    on_success: never
    on_failure: never