# make_test_fixtures.R
#
# Regenerates the small sample data files used by the test suite, which live in
# tests/testthat/fixtures/.
#
# WHY THESE EXIST
# ---------------
# Several CSHShydRology functions are file/URL readers: ch_read_ECDE_flows(),
# ch_get_ECDE_metadata(), ch_read_AHCCD_daily() and ch_read_AHCCD_monthly().
# They cannot be tested by passing a data frame -- they need an actual file in a
# specific layout. Historically that meant a test either downloaded a file (slow,
# and fails whenever the remote host is down -- the very fragility we want the
# test suite to warn us about, not be broken by) or was simply never written.
#
# Instead we keep tiny, format-faithful sample files in the repository. They are
# small enough to read at a glance, they make the expected file layout explicit,
# and the tests run offline on CRAN.
#
# PROVENANCE
# ----------
# The ECDE flow and metadata fixtures are derived from data already shipped with
# this package (CAN05AA008 and HYDAT_list), so they introduce no new data of
# uncertain licence. The AHCCD fixtures are synthetic: the values are made up,
# but the file layout (bilingual header lines, fixed-width columns, -9999.9
# missing-value flags, quality-flag characters) reproduces the real
# Environment and Climate Change Canada AHCCD files that the readers target.
#
# HOW TO REGENERATE
# -----------------
# From the package root:
#
#   Rscript data-raw/make_test_fixtures.R
#
# The script is deterministic -- rerunning it produces byte-identical files.

library(CSHShydRology)

fixture_dir <- file.path("tests", "testthat", "fixtures")
dir.create(fixture_dir, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------------
# 1. ECDE daily flows  ->  ecde_flows_sample.csv
#
# Layout produced by the Windows program ECDataExplorer, as consumed by
# ch_read_ECDE_flows(): one header line, then ID,PARAM,Date,Flow,SYM rows, then
# three trailing disclaimer lines that the reader drops.
# ---------------------------------------------------------------------------

data("CAN05AA008", package = "CSHShydRology")

# Take one full water year so that day-of-year and water-year helpers have a
# complete cycle to chew on, plus a couple of rows carrying quality flags.
ecde <- CAN05AA008[CAN05AA008$Date >= as.Date("2000-01-01") &
                     CAN05AA008$Date <= as.Date("2000-12-31"), ]

ecde_lines <- c(
  " ID,PARAM,Date,Flow,SYM",
  paste(ecde$ID, ecde$PARAM,
        format(ecde$Date, "%Y/%m/%d"),
        ecde$Flow, ecde$SYM, sep = ","),
  "Disclaimer: these are sample values for testing only.",
  "Avertissement : donnees d'exemple pour les tests seulement.",
  "Generated by data-raw/make_test_fixtures.R"
)

writeLines(ecde_lines, file.path(fixture_dir, "ecde_flows_sample.csv"))

# ---------------------------------------------------------------------------
# 2. ECDE station metadata  ->  ecde_metadata_sample.tb0
#
# ch_get_ECDE_metadata() does read.table(skip = 96, sep = " "), so the file
# needs exactly 96 lines of preamble followed by 21 space-separated fields per
# station. Station names contain spaces and so must be quoted.
# ---------------------------------------------------------------------------

data("HYDAT_list", package = "CSHShydRology")

meta_stations <- c("05AA008", "05BB001", "05BA001")
meta_rows <- HYDAT_list[HYDAT_list$Station %in% meta_stations, ]
meta_rows <- meta_rows[match(meta_stations, meta_rows$Station), ]

# ECDE writes a long EnSim-style preamble; its content is irrelevant to the
# reader, which skips a fixed 96 lines. Keep it obviously inert.
preamble <- c(
  "#########################################################################",
  "# EnSim / ECDataExplorer favourite-stations export (sample for testing)",
  "# Generated by data-raw/make_test_fixtures.R",
  "#########################################################################"
)
preamble <- c(preamble, rep("#", 96 - length(preamble)))
stopifnot(length(preamble) == 96)

# Column 2 is the "Fav" flag, which the reader drops.
meta_lines <- paste(
  meta_rows$Station,
  1,
  paste0("\"", meta_rows$StationName, "\""),
  meta_rows$HYDStatus,
  meta_rows$Prov,
  meta_rows$Latitude,
  meta_rows$Longitude,
  meta_rows$DrainageArea,
  meta_rows$Years,
  meta_rows$From,
  meta_rows$To,
  meta_rows$Reg.,
  meta_rows$Flow,
  meta_rows$Level,
  meta_rows$Sed,
  meta_rows$OperSched,
  meta_rows$RealTime,
  meta_rows$RHBN,
  meta_rows$Region,
  paste0("\"", meta_rows$Datum, "\""),
  paste0("\"", meta_rows$Operator, "\"")
)

writeLines(c(preamble, meta_lines),
           file.path(fixture_dir, "ecde_metadata_sample.tb0"))

# ---------------------------------------------------------------------------
# 3. AHCCD daily  ->  dx_ahccd_daily_sample.txt (tmax)
#                     dt_ahccd_daily_sample.txt (total precipitation)
#
# ch_read_AHCCD_daily() infers the variable from the file name ("dx" = tmax,
# "dm" = tmean, "dn" = tmin, "dt" = precip, "dr" = rain, "ds" = snow) and
# infers how many lines to skip by counting header lines that mention
# "updated"/"jusqu" (file header) and "year"/"annee" (column header). The real
# files have a single bilingual "Updated to ... / Mise a jour jusqu'a ..." line,
# which therefore counts as two, giving three skipped lines in total.
#
# Each data row is: year (width 5, leading space), month (width 3), one spare
# character, then 31 (value, flag) pairs. Value width is 7 for temperatures and
# 8 for precipitation. Missing days are -9999.9.
# ---------------------------------------------------------------------------

ahccd_daily_header <- function(varname_en, varname_fr) {
  c(
    paste0(varname_en, " / ", varname_fr,
           ", Stn_Name=SAMPLE STATION, Prov=ALTA, Stn_Id=9999999"),
    "Updated to December 2020 / Mise a jour jusqu'a decembre 2020",
    paste0("Year Mo ", paste(sprintf("Day%02d", 1:31), collapse = " "))
  )
}

days_in_month <- function(year, month) {
  as.integer(format(as.Date(paste(year, month + 1, "01", sep = "-")) - 1, "%d"))
}

# Deterministic pseudo-values: no RNG, so reruns are byte-identical.
ahccd_daily_body <- function(years, value_width, base, amplitude) {
  out <- character(0)
  for (yr in years) {
    for (mo in 1:12) {
      ndays <- if (mo == 12) 31L else days_in_month(yr, mo)
      vals <- numeric(31)
      flags <- character(31)
      for (d in 1:31) {
        if (d <= ndays) {
          doy <- as.numeric(format(as.Date(sprintf("%d-%02d-%02d", yr, mo, d)), "%j"))
          vals[d] <- round(base + amplitude * sin(2 * pi * (doy - 100) / 365), 1)
          # Sprinkle a few estimated ("E") values so flag handling is exercised.
          flags[d] <- if (d == 15 && mo %% 6 == 0) "E" else " "
        } else {
          vals[d] <- -9999.9
          flags[d] <- " "
        }
      }
      # One genuinely missing observation, to exercise the -999 -> NA recoding.
      if (yr == years[1] && mo == 3) {
        vals[10] <- -9999.9
      }
      fmt <- paste0("%", value_width, ".1f%s")
      cells <- paste0(sprintf(fmt, vals, flags), collapse = "")
      out <- c(out, sprintf("%5d%3d %s", yr, mo, cells))
    }
  }
  out
}

writeLines(
  c(ahccd_daily_header("Daily Maximum Temperature (C)",
                       "Temperature maximale quotidienne (C)"),
    ahccd_daily_body(2018:2020, value_width = 7, base = 8, amplitude = 14)),
  file.path(fixture_dir, "dx_ahccd_daily_sample.txt")
)

writeLines(
  c(ahccd_daily_header("Daily Total Precipitation (mm)",
                       "Precipitation totale quotidienne (mm)"),
    ahccd_daily_body(2018:2020, value_width = 8, base = 2.5, amplitude = 2)),
  file.path(fixture_dir, "dt_ahccd_daily_sample.txt")
)

# ---------------------------------------------------------------------------
# 4. AHCCD monthly  ->  mt_ahccd_monthly_sample.txt (total precipitation)
#                       mn_ahccd_monthly_sample.txt (minimum temperature)
#
# ch_read_AHCCD_monthly() uses read.csv() after the same header-counting trick,
# except that the French column-header keyword is "hiver" rather than "annee".
# Each data row is: year, then 12 (value, flag) pairs = 25 comma-separated
# fields.
#
# The "mn" (tmin) fixture is deliberately included because that branch of the
# reader was broken -- see tests/testthat/test-ch_read_AHCCD_monthly.R.
# ---------------------------------------------------------------------------

# NOTE ON HEADER LINE COUNTS
# The reader counts keywords, not lines: "updated" and "jusqu" each add one
# file-header line, and "year" and "hiver" each add one column-header line. The
# bilingual "Updated ... / Mise a jour jusqu'a ..." line therefore counts as two,
# so the English and French column headers must sit on separate lines for the
# total (4) to match the actual number of header lines. Putting "Year" and
# "hiver" on one line makes the reader skip 4 lines when only 3 are header,
# silently swallowing the first year of data.
ahccd_monthly_header <- function(varname_en, varname_fr) {
  c(
    paste0(varname_en, " / ", varname_fr,
           ", Stn_Name=SAMPLE STATION, Prov=ALTA, Stn_Id=9999999"),
    "Updated to December 2020 / Mise a jour jusqu'a decembre 2020",
    paste0("Year,", paste(month.abb, collapse = ",")),
    paste0("Annee,", paste(c(month.abb[1:11], "hiver"), collapse = ","))
  )
}

ahccd_monthly_body <- function(years, base, amplitude) {
  out <- character(0)
  for (yr in years) {
    cells <- character(0)
    for (mo in 1:12) {
      val <- round(base + amplitude * sin(2 * pi * (mo - 4) / 12), 1)
      # One missing month, to exercise the -999 -> NA recoding.
      if (yr == years[1] && mo == 2) val <- -9999.9
      flag <- if (mo == 7) "E" else " "
      cells <- c(cells, format(val, nsmall = 1, trim = TRUE), flag)
    }
    out <- c(out, paste(c(yr, cells), collapse = ","))
  }
  out
}

writeLines(
  c(ahccd_monthly_header("Monthly Total Precipitation (mm)",
                         "Precipitation totale mensuelle (mm)"),
    ahccd_monthly_body(2011:2020, base = 55, amplitude = 30)),
  file.path(fixture_dir, "mt_ahccd_monthly_sample.txt")
)

writeLines(
  c(ahccd_monthly_header("Monthly Mean Minimum Temperature (C)",
                         "Temperature minimale moyenne mensuelle (C)"),
    ahccd_monthly_body(2011:2020, base = -2, amplitude = 12)),
  file.path(fixture_dir, "mn_ahccd_monthly_sample.txt")
)

message("Fixtures written to ", fixture_dir, ":")
message(paste(" -", list.files(fixture_dir)), sep = "\n")
